### ISSUE TITLE
JS: Utiliser les icônes de bootstrap-vue au lieu de vue-awesome

### ISSUE THREAD

**Issue by Supermanu** [ISLNamur/happyschool#22]

**Comment by pjacquemin** [comment]
Bonjour @Supermanu ,

Je suis un parent d'élève à Saint-Louis et programmeur.
J'aimerais participer à votre projet. Puis je prendre cette issue ?

Cordialement.
Patrick Jacquemin

**Comment by Supermanu** [comment]
Bonjour,
C'est chouette de voir un parent intéressé par le projet :). Concernant cette issue, elle est déjà résolue, j'ai juste oublié de la fermer. Je peux toutefois faire d'autres propositions "good first issue" (côté frontend).

S'il y a le moindre problème pour mettre en place l'environnement de développement, j'ai créé une[ instance Zulip](https://happyschool.zulipchat.com/) où discuter. Par ailleurs, à force d'être le seul contributeur, il est possible que la documentation ne soit pas à jour et que la mise place trébuche à quelques endroits. Donc, il ne faut surtout pas hésiter à faire un retour, j'essayerai d'être le plus réactif possible.

**Comment by pjacquemin** [comment]
OK c'est parfait. Je me suis refait un PC avec Ubuntu ce matin pour pouvoir travailler sur ce projet. 
J'envisage de commencer dans le courant de la semaine prochaine.
J'ai déjà pu faire un tour dans la documentation pour l'installation du projet avec Docker et cela m'a semblé bien documenté.

Merci pour votre retour et bon week-end ;-)
